# Generated by Django 2.1.2 on 2018-10-09 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSpaces',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular booking space', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('c', 'Cancelled'), ('p', 'Passed'), ('u', 'Upcoming'), ('i', 'In Progress')], default='u', help_text='meetup availability', max_length=1)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the meetup', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a meetup category (e.g. Javascript meetup)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='meetup',
            name='meetupCategory',
            field=models.ManyToManyField(help_text='Select a MeetupCategory for this Meetup', to='meetups_list.MeetupCategory'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetups_list.Organiser'),
        ),
        migrations.AddField(
            model_name='bookingspaces',
            name='meetup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetups_list.Meetup'),
        ),
    ]
